package orchestrator

import (
	"context"
	"fmt"
	"log/slog"
	"strings"

	"github.com/auto-code-os/auto-code-os/server/pkg/models"
)

// PRGenerator builds AI-generated PR summaries and risk assessments.
type PRGenerator struct{}

func NewPRGenerator() *PRGenerator {
	return &PRGenerator{}
}

// GenerateSummary creates a structured PR summary from task data and changed files.
func (g *PRGenerator) GenerateSummary(ctx context.Context, task *models.Task, changedFiles []string) *models.PRSummary {
	title := fmt.Sprintf("[Auto Code OS] %s", task.Title)

	// Build the PR body.
	var body strings.Builder
	body.WriteString("## Summary\n\n")
	body.WriteString(fmt.Sprintf("Automated changes for task: **%s**\n\n", task.Title))
	if task.Description != "" {
		body.WriteString(fmt.Sprintf("### Description\n%s\n\n", task.Description))
	}

	body.WriteString("### Changed Files\n")
	for _, f := range changedFiles {
		body.WriteString(fmt.Sprintf("- `%s`\n", f))
	}
	body.WriteString("\n")

	// Risk assessment based on task complexity and file count.
	riskLevel, riskReason := assessRisk(task, changedFiles)
	body.WriteString(fmt.Sprintf("### Risk Assessment\n**Level:** %s\n**Reason:** %s\n\n", riskLevel, riskReason))

	body.WriteString("---\n")
	body.WriteString("*This PR was generated by Auto Code OS.*\n")

	slog.Info("pr summary generated", "task_id", task.ID, "files", len(changedFiles), "risk", riskLevel)

	return &models.PRSummary{
		Title:        title,
		Body:         body.String(),
		ChangedFiles: changedFiles,
		RiskLevel:    riskLevel,
		RiskReason:   riskReason,
		Status:       models.PRStatusOpen,
	}
}

// assessRisk evaluates the risk level of a PR based on task complexity and scope.
func assessRisk(task *models.Task, changedFiles []string) (string, string) {
	fileCount := len(changedFiles)

	// Check for critical file patterns.
	hasMigration := false
	hasConfig := false
	for _, f := range changedFiles {
		if strings.Contains(f, "migration/") {
			hasMigration = true
		}
		if strings.Contains(f, "config") || strings.Contains(f, ".env") || strings.Contains(f, "docker") {
			hasConfig = true
		}
	}

	switch {
	case hasMigration && task.Complexity == models.TaskComplexityHard:
		return models.PRRiskCritical, "Database migration in a hard-complexity task requires careful review"
	case hasMigration:
		return models.PRRiskHigh, "Contains database migration files"
	case task.Complexity == models.TaskComplexityHard || fileCount > 15:
		return models.PRRiskHigh, fmt.Sprintf("Hard complexity task affecting %d files", fileCount)
	case hasConfig:
		return models.PRRiskMedium, "Modifies configuration or infrastructure files"
	case task.Complexity == models.TaskComplexityMedium || fileCount > 5:
		return models.PRRiskMedium, fmt.Sprintf("Medium complexity task affecting %d files", fileCount)
	default:
		return models.PRRiskLow, fmt.Sprintf("Simple change affecting %d files", fileCount)
	}
}
